export default {
  login: "igee-17",
  id: 89357459,
  node_id: "MDQ6VXNlcjg5MzU3NDU5",
  avatar_url: "https://avatars.githubusercontent.com/u/89357459?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/igee-17",
  html_url: "https://github.com/igee-17",
  followers_url: "https://api.github.com/users/igee-17/followers",
  following_url: "https://api.github.com/users/igee-17/following{/other_user}",
  gists_url: "https://api.github.com/users/igee-17/gists{/gist_id}",
  starred_url: "https://api.github.com/users/igee-17/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/igee-17/subscriptions",
  organizations_url: "https://api.github.com/users/igee-17/orgs",
  repos_url: "https://api.github.com/users/igee-17/repos",
  events_url: "https://api.github.com/users/igee-17/events{/privacy}",
  received_events_url: "https://api.github.com/users/igee-17/received_events",
  type: "User",
  site_admin: false,
  name: "Olaleye Igbagbo",
  company: null,
  blog: "",
  location: "Ibadan",
  email: null,
  hireable: null,
  bio: "Frontend Developer",
  twitter_username: "i_gee17",
  public_repos: 13,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2021-08-22T19:19:29Z",
  updated_at: "2022-07-19T23:05:15Z",
};
